# Generated by Django 4.2.3 on 2023-08-11 07:41

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("reviews", "0002_alter_review_experiences_alter_review_rooms_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="review",
            old_name="experiences",
            new_name="experience",
        ),
        migrations.RenameField(
            model_name="review",
            old_name="rooms",
            new_name="room",
        ),
    ]
