# Generated by Django 4.2.3 on 2023-11-01 11:20

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "experiences",
            "0003_alter_experience_category_alter_experience_host_and_more",
        ),
        ("rooms", "0006_alter_room_amenities"),
        ("wishlists", "0003_alter_wishlist_experiences_alter_wishlist_rooms"),
    ]

    operations = [
        migrations.AlterField(
            model_name="wishlist",
            name="experiences",
            field=models.ManyToManyField(
                blank=True, related_name="wishlists", to="experiences.experience"
            ),
        ),
        migrations.AlterField(
            model_name="wishlist",
            name="rooms",
            field=models.ManyToManyField(
                blank=True, related_name="wishlists", to="rooms.room"
            ),
        ),
    ]
