# Generated by Django 4.2.3 on 2024-12-14 11:02

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("bookings", "0002_alter_booking_experience_alter_booking_room_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="booking",
            name="not_canceled",
            field=models.BooleanField(default=False),
        ),
    ]
